Edits for MedicationDispense and Medication
gematik/api-erp pull request #149
Opened 2024-05-13 08:32 UTC by florianschoffke

Bitte um review der Änderungen zum Mapping der Workflow Medication

2024-05-14 11:26 UTC, florianschoffke commented on docs/erp_epa_mapping_details/EPAMedicationDispense.html
> +    <h2>Mapping: GEM_ERP_PR_MedicationDispense in EPAMedicationDispense</h2>
done

2024-05-14 11:26 UTC, florianschoffke commented on docs/erp_epa_mapping_details/EPAMedicationDispense.html
> +                <th>GEM_ERP_PR_MedicationDispense</th>
done

2024-05-15 07:22 UTC, SvenSommer commented on docs/erp_epa_mapping_details/EPAMedicationDispense.html
> +    <h2>Mapping: GEM_ERP_PR_MedicationDispense|1.4 in EPAMedicationDispense</h2>
Ich möchte hier nicht zeigen, wie die "neue" MedicationDispense in der kommenden Version 1.4 in die ePA MedicationDispense gemappt wird, sondern die "aktuelle" MedicationDispense in der Version 1.2.
Diese Operation soll veranschaulichen, wie der E-Rezept-Fachdienst in der Übergangszeit mappt und aufzeigen, wie AVS von der "alten" in die "neue" Welt überführt werden.
Die Version 1.4 der ePA MedicationDispense ist ebenfalls interessant, hilft jedoch weder dem E-Rezept-Fachdienst-Team noch den AVS in der aktuellen Situation.

2024-05-15 07:24 UTC, SvenSommer requested changes
Ich möchte hier nicht zeigen, wie die "neue" MedicationDispense in der kommenden Version 1.4 in die ePA MedicationDispense gemappt wird, sondern die "aktuelle" MedicationDispense in der Version 1.2.
Das Mapping der MedicationDispense soll veranschaulichen, wie der E-Rezept-Fachdienst in der Übergangszeit die Dispense mapped und aufzeigen, wie AVS von der "alten" in die "neue" Welt überführt werden.
Die Version 1.4 der ePA MedicationDispense ist ebenfalls interessant, hilft jedoch weder dem E-Rezept-Fachdienst-Team noch den AVS in der aktuellen Situation.

2024-05-15 07:25 UTC, SvenSommer commented on docs/erp_epa_mapping_details/EPAMedicationDispense.html
> +    <h2>Mapping: GEM_ERP_PR_MedicationDispense|1.4 in EPAMedicationDispense</h2>
Außerdem bitte noch die Version und den Stand der Information mit angeben!
`    <p>Version: 0.10</p>
    <p>Stand: 15.05.2024</p>`

2024-07-05 06:11 UTC, closed without merging