Korrektur FHIR Timeline
gematik/api-erp pull request #153
Opened 2024-05-16 05:38 UTC by florianschoffke

PKV Abgabedaten erhalten kein Update zum 01.11. 
Das wurde korrigiert

2024-05-16 06:19 UTC, Hendrejvr approved these changes

2024-05-16 06:41 UTC, SvenSommer requested changes

2024-05-16 06:41 UTC, SvenSommer commented on puml/fhir_version_timeline.puml
> +concise "S_KBV_DMP" as DMP <<kbvcolor>>
Mit den Schlüsseltabellen und deren impliziter Kennzeichnung mit der “S_*”-Notation ist die Grafik leider nicht ohne weitere Erklärungen zugänglich. Ich schlage vor, die Grafik um eine detaillierte Legende oder einen Erklärungstext zu ergänzen, der auf die jeweiligen Simplifier-Projekte der angezeigten Pakete verweist. Vermutlich genügt eine einfache Tabelle in der folgenden Form:

| Paketname                              | Beschreibung                                           | Simplifier-Projekt                                    |
|----------------------------------------|--------------------------------------------------------|-------------------------------------------------------|
| de.gkvsv.eRezeptAbrechnungsdaten       |                                                        |                                                       |
| kbv.ita.erp                            | eRezept-Projekt der KBV                                | [eRezept](https://simplifier.net/eRezept/)            |
| S_KBV_DARREICHUNGSFORM                 |                                                        |                                                       |
| S_KBV_DMP                              |                                                        |                                                       |
| de.abda.eRezeptAbgabedaten             |                                                        |                                                       |
| de.abda.eRezeptAbgabedatenPKV          |                                                        |                                                       |
| de.gematik.erezept-workflow.r4         | E-Rezept-Workflow-Projekt der gematik                  | [E-Rezept-Workflow](https://simplifier.net/erezept-workflow) |
| de.gematik.erezept-patientenrechnung.r4| E-Rezept-Patientenrechnung - Abrechnungsinformationen des E-Rezeptes für den Patienten - der gematik | [E-Rezept-Patientenrechnung](https://simplifier.net/erezept-patientenrechnung) |

2024-05-21 06:59 UTC, SvenSommer approved these changes

2024-05-21 11:31 UTC, florianschoffke reviewed
> Please make it more clear that profiles with Version 1.4 have a transition period of 3 months. 

Done, can you check again?

2024-05-21 11:46 UTC, merged