Workaround für wenn der $activate-Aufruf keine Response zurückgibt
gematik/api-erp pull request #169
Opened 2024-07-09 12:07 UTC by Hendrejvr

Dieser Pull Request dient als Workaround, falls der $activate-Aufruf keine Response zurückgibt und das PVS den Aufruf wiederholen sollte.

2024-07-10 12:42 UTC, florianschoffke requested changes

2024-07-10 12:42 UTC, florianschoffke commented on docs/erp_bereitstellen.adoc
> +NOTE: Für den Fall, dass das Clientsystem beim Aufruf der Operation keinen Response erhält, soll der Aufruf wiederholt werden. Wenn im Response ein Fehler 403 mit dem OperationOutcome "Task not in st
200 oder 201?

2024-07-10 12:42 UTC, florianschoffke commented on docs/erp_bereitstellen.adoc
> +NOTE: Für den Fall, dass das Clientsystem beim Aufruf der Operation keinen Response erhält, soll der Aufruf wiederholt werden. Wenn im Response ein Fehler 403 mit dem OperationOutcome "Task not in st
Dieser Fehler und die Beschreibung müssten noch in https://github.com/gematik/api-erp/blob/master/docs/erp_statuscodes.adoc beschrieben werden

2024-07-10 13:09 UTC, Hendrejvr commented on docs/erp_bereitstellen.adoc
> +NOTE: Für den Fall, dass das Clientsystem beim Aufruf der Operation keinen Response erhält, soll der Aufruf wiederholt werden. Wenn im Response ein Fehler 403 mit dem OperationOutcome "Task not in st
Bei $activate ist das 200, oder? 
Laut [hier](https://github.com/gematik/api-erp/blob/master/docs/erp_bereitstellen.adoc#e-rezept-vervollst%C3%A4ndigen-und-task-aktivieren) ist es 200

2024-07-11 04:25 UTC, florianschoffke commented on docs/erp_bereitstellen.adoc
> +NOTE: Für den Fall, dass das Clientsystem beim Aufruf der Operation keinen Response erhält, soll der Aufruf wiederholt werden. Wenn im Response ein Fehler 403 mit dem OperationOutcome "Task not in st
Ja passt, habe es auf der RU auch getestet. 👍

2024-07-11 06:25 UTC, florianschoffke approved these changes

2024-07-11 06:26 UTC, merged