Hinweise für VSDM Fehlerausgaben
gematik/api-erp pull request #52
Opened 2023-04-20 13:41 UTC by florianschoffke

2023-04-20 17:37 UTC, SvenSommer requested changes

2023-04-20 17:37 UTC, SvenSommer commented on docs_sources/erp_alternative_zuweisung.adoc
Warum wird das wieder entfernt?

2023-04-20 17:37 UTC, SvenSommer commented on images/puml_az_apotheke.png
Gab es hier wirklich Änderungen?

2023-04-21 05:04 UTC, florianschoffke commented on docs_sources/erp_alternative_zuweisung.adoc
Diese nicht source datei war in docs_sources drin und nicht im docs ordner. 
Daher habe ich dieses Duplikat gelöscht. im docs Ordner ist das eigentliche

2023-04-21 05:05 UTC, florianschoffke commented on images/puml_az_apotheke.png
Scheint wieder dieses Ding mit dem Skript zu sein, dass das manchmal dann anzeigt dass sie neu sind. Vielleicht liegt das an den puml Dateien die jetzt wieder drin sind...

2023-04-21 06:19 UTC, SvenSommer approved these changes

2023-04-21 06:25 UTC, merged